mysql: 
  host:81.68.228.223
  port:3306
  db:gvb_db
  user:gvb_db
  password:F2EYnicEF3Xw3Shb
  log_level:dev

logger:
  level:info
  prefix:'[gins]'
  dorector:log
  show_line:true
  log_in_console:true

system:
  host:"0.0.0.0"
  port:8080
  env:dev